@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(passenger, "Passenger")
Person(driver, "Driver")
Container(loadBalancer, "Load Balancer", "Nginx", "Uses round robin")
Container(apiGateway, "API Gateway", "", "")
ContainerQueue(messageQueue, "Events queue", "Kafka", "Message queue for events by tiny URLs")

System_Boundary(coreSystem, "Core system") {
    Container(matchingService, "Matching Service", " ", "", $tags="webApp")
    ContainerDb(matchingDatabase, "Matching database", "Tarantool", "",  $tags="db")
    Container(notificationService, "Notification Service", " ", "", $tags="webApp")
    Container(geoService, "Geo Service", " ", "", $tags="webApp")
    ContainerDb(geoDatabase, "Geo database", "Tarantool", "",  $tags="db")
}

System_Boundary(rideSystem, "Ride system") {
    Container(rideService, "Ride Service", " ", "", $tags="webApp")
    ContainerDb(rideDatabase, "Ride database", "Tarantool", "",  $tags="db")
}

System_Boundary(analyticalSystem, "Analythical system") {
    Container(historyService, "History Service", " ", "", $tags="webApp")
    ContainerDb(historyDatabase, "History database", "Clickhouse", "",  $tags="db")
}

Rel(passenger, loadBalancer, "Call API methods, aimed for passenger use-cases", "REST")
Rel(driver, loadBalancer, "Call API methods, aimed for driver use-cases", "REST")

Rel(loadBalancer, apiGateway, " ", "")
Rel(apiGateway, matchingService, "", "")


Rel(matchingService, matchingDatabase, "")
Rel(matchingService, notificationService, "")
Rel(matchingService, geoService, "")
Rel(geoService, geoDatabase, "")
Rel(notificationService, passenger, "Notifies passenger", "REST")
Rel(notificationService, driver, "Notifies driver", "REST")
Rel(matchingService, rideService, "")
Rel(rideService, messageQueue, "Publishes ride info for history and analytics")
Rel(historyService, messageQueue, "Subscribes for ride info for history and analytics")


@enduml